# Generated by Django 3.1.2 on 2021-06-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('head0', models.CharField(default='', max_length=50)),
                ('chead0', models.CharField(default='', max_length=1000)),
                ('head1', models.CharField(default='', max_length=50)),
                ('chead1', models.CharField(default='', max_length=1000)),
                ('head2', models.CharField(default='', max_length=50)),
                ('chead2', models.CharField(default='', max_length=1000)),
                ('image_nm', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
