# Generated by Django 3.1.2 on 2021-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobileno', models.IntegerField(default=0)),
                ('feedback', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
